Remove harmful hiding of exception cause
Before:
```
$ STYX_CLI_HOST=typo.in.hostname styx events comp workfl 2018-04-23
Client error: Request failed: RequestValue{method=GET, uri=https://typo.in.hostname/api/v3/status/events/comp/workfl/2018-04-23, parameters={}, headers={}, service=Optional.empty, payload=Optional.empty, ttl=Optional.empty}
```

After:
```
$ STYX_CLI_HOST=typo.in.hostname styx events comp workfl 2018-04-23
com.spotify.styx.client.ClientErrorException: Request failed: RequestValue{method=GET, uri=https://typo.in.hostname/api/v3/status/events/comp/workfl/2018-04-23, parameters={}, headers={}, service=Optional.empty, payload=Optional.empty, ttl=Optional.empty}
        at com.spotify.styx.client.StyxApolloClient.lambda$executeRequest$12(StyxApolloClient.java:447)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at com.spotify.apollo.http.client.TransformingCallback.onFailure(TransformingCallback.java:58)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Request Request{method=GET, url=https://typo.in.hostname/api/v3/status/events/comp/workfl/2018-04-23, tag=null} failed
        at com.spotify.apollo.http.client.TransformingCallback.onFailure(TransformingCallback.java:57)
        ... 5 more
Caused by: java.net.UnknownHostException: typo.in.hostname: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
        at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.access$100(Call.java:35)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
        ... 4 more
```